---
- name: Remove Zabbix repo package
  ansible.builtin.apt:
    name: zabbix-release
    state: absent

- name: Remove Zabbix repo file
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/apt/sources.list.d/zabbix.list
    - /etc/apt/sources.list.d/zabbix-tools.list

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install Zabbix Repo
  ansible.builtin.apt:
    deb: https://repo.zabbix.com/zabbix/7.0/debian/pool/main/z/zabbix-release/zabbix-release_latest_7.0+debian12_all.deb
    state: present
    
- name: Install Zabbix Agent
  ansible.builtin.package:
    name: zabbix-agent
    state: present

- name: Ensure Server is set (not commented)
  ansible.builtin.lineinfile:
    path: /etc/zabbix/zabbix_agentd.conf
    regexp: '^Server='
    line: "Server={{ zabbix_server }}"
    insertafter: EOF

- name: Ensure ServerActive is set (not commented)
  ansible.builtin.lineinfile:
    path: /etc/zabbix/zabbix_agentd.conf
    regexp: '^ServerActive='
    line: "ServerActive={{ zabbix_server }}"
    insertafter: EOF

- name: Enable and start Zabbix Agent2
  ansible.builtin.service:
    name: zabbix-agent
    enabled: true
    state: restarted