---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/bookmarks

- Developer:
    - Github:
        - abbr: GH
          href: https://github.com/

- Various:
    - Home Awesome:
        - abbr: HA
          href: https://www.awesome-homelab.com/products
