---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Applications (Proxy):
    - Git Lab:
        href: http://gitlab.home/
        description: Git Lab Server
    - Home Assistant:
        href: http://homeassistant.home/
        description: Home Assistant Administration
    - Music Assistant:
        href: http://homeassistant-01.home:8123/d5369777_music_assistant_beta/ingress
        description: Music Assistant
    - Paperless:
        href: http://paperless.home
        description: Document Management System
    - Plex:
        href: http://plex-01.home:32400/web
        description: Media Server

- Infrastructure:
    - PHPIPAM:
        href: http://utility-01.home:8080/phpipam
        description: IP Management
    - Portainer:
        href: https://utility-01.home:9443
        description: Container management
    - Proxmox Production:
        href: https://proxmox-1.home:8006
        description: VM/CT Management
    - Proxmox Production Repl:
        href: https://proxmox-1-repl.home:8006
        description: VM/CT Management
    - Prometheus:
        href: http://utility-01.home:9090
        description: Time Series DB
    - QNAP:
        href: https://192.168.1.229
        description: QNAP
    - Traefik Dashboard:
        href: https://proxy-01.home/
        description: Traefik Dashboard
    - Unifi:
        href: https://192.168.1.1
        description: Network Management
    - Zabbix:
        href: http://zabbix-01.home/
        description: Systems Monitoring
    
- Utility:
    - Beszel:
        href: http://utility-01.home:8090/
        description: Beszel Monitoring System
    - Dozzel (Utility-01):
        href: http://utility-01.home:8091/
        description: Dozzel Container logs
    - Dozzel (Docker-03):
        href: http://docker-03.home:8091/
        description: Dozzel Container logs
    - Dozzel (Proxy-01):
        href: http://proxy-01.home:8091/
        description: Dozzel Container logs
    - Grafana:
        href: http://utility-01.home:3002/
        description: Grafana
    - HP Printer (Office):
        href: https://192.168.1.221/
        description: HP Printer Configuration
    - Home Page:
        href: http://utility-01.home:3000/
        description: Homepage is awesome
    - Home Assistant:
        href: http://homeassistant-01.home:8123/
        description: Home Assistant Administration
    - Home Assistant2:
        href: http://homeassistant-02.home:8123/
        description: Home Assistant Administration (MA2)
    - Home Assistant Border Router UI:
        href: http://homeassistant-01.home:8080/
        description: Home Assistant Border Router UI
    - Music Assistant:
        href: http://homeassistant-01.home:8123/d5369777_music_assistant_beta/ingress
        description: Music Assistant
    - SMLight SLZB-06-ZIGBEE:
        href: http://192.168.20.201:80
        description: Zigbee Ethernet
    - SMLight SLZB-06-MATTER:
        href: http://192.168.20.226:80
        description: Matter Ethernet
    - Uptime Kuma:
        href: http://utility-01.home:3001/dashboard
        description: Monitoring
    - Whoami:
        href: https://whoami.proxy-01.home/
        description: Whoami Test Service
- Lab:
    - Siglent Scope:
        href: http://192.168.1.213/
        description: Scope Remote Control
- Non Proxy Locations:
    - Paperless:
        href: http://docker-03.home:8000
        description: Document Management System


