- name: Proxmox baseline configuration
  hosts: proxmox_cluster
  become: true

  roles:
    - proxmox_repos
    - zfs-auto-snapshot
    - pve_cluster_backups
    - proxmox_zfs_fs
    - proxmox_exports
    - proxmox_validate
    - proxmox_preferred_hosts
    - proxmox_replication
    - proxmox_root_shell
    - zabbix_agent
    
- name: Linux Server Processing
  hosts: linux_servers
  become: true

  roles:
    - linux_patch
    - linux_standard_tasks
    - zabbix_agent

- name: Zabbix Server Processing
  hosts: zabbix_servers
  become: true

  roles:
    - zabbix_patch


