---
- name: Update apt cache
  apt:
    update_cache: yes
  tags: repos

- name: Ensure zfs-auto-snapshot is installed
  apt:
    name: zfs-auto-snapshot
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: Configure ZFS auto snapshots (PROXMOX)
  ansible.builtin.import_tasks: proxmox.yml

- name: Configure ZFS auto snapshots (NAS)
  ansible.builtin.import_tasks: nas.yml
