#networks:
#  uptime-kuma_net:
#    driver: host
services:
  uptime-kuma:
#    networks:
#      - uptime-kuma_net
    image: docker.io/louislam/uptime-kuma:2
    ports:
      - 3001:3001
    volumes:
      - ./volumes/uptime-kuma:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
