version: "3"
networks:
  phpipam_net:
    driver: bridge
services:
  web:
    networks:
      - phpipam_net
    build: ./containers/web
    ports:
      - "8080:80"
    volumes:
      - ./volumes/html:/var/www/html


