---
- name: Configure QEMU Guest
  ansible.builtin.import_tasks: qemu.yml

- name: Docker
  ansible.builtin.import_tasks: docker.yml

- name: Apache2 utils
  ansible.builtin.import_tasks: apache.yml

- name: SSHD Configuration
  ansible.builtin.import_tasks: sshd.yml