---
- name: Configure QEMU Guest
  ansible.builtin.import_tasks: qemu.yml

- name: Docker
  ansible.builtin.import_tasks: docker.yml

- name: Apache2 utils
  ansible.builtin.import_tasks: apache.yml

- name: SSHD Configuration
  ansible.builtin.import_tasks: sshd.yml

- name: Install Custom Aliases and Exports
  ansible.builtin.import_tasks: aliases.yml

- name: Install net-tools
  ansible.builtin.apt:
    name: net-tools
    state: present
    update_cache: true
