all:
  children:
    proxmox_cluster:
      vars:
        proxmox_release: bookworm
        proxmox_admin_user: hcamacho
        cluster_backup_keep_count: 90
      hosts:
        proxmox-1:
          cluster: true
          nas: false
          zfs_auto_snapshot: true
        proxmox-2:
          cluster: true
          nas: false
          zfs_auto_snapshot: true
        proxmox-3:
          cluster: true
          nas: false
          zfs_auto_snapshot: true
        proxmox-4:
          cluster: true
          nas: false
          zfs_auto_snapshot: true
        proxmox-6:
          cluster: true
          nas: false
          zfs_auto_snapshot: true
        proxmox-7:
          cluster: true
          nas: true
          zfs_auto_snapshot: true
        proxmox-8:
          cluster: true
          nas: false
          zfs_auto_snapshot: false
          replication_destination: true
    linux_servers:
      vars:
        ansible_user: ubuntu
        ansible_become: true
        ansible_become_method: sudo
      hosts:
        collector:
        db01:
          zabbix_enable_mysql: true
        docker-03:
          docker: true
        plex-01:
        proxy-01:
          docker: true
        utility-01:
    zabbix_servers:
      vars: 
        ansible_python_interpreter: /usr/bin/python3.11
      hosts:
        zabbix-01:




